[project]
name = "srai"
version = "0.1.0"
description = ""
authors = [
    {name = "srai", email = "example@gmail.com"},
]
dependencies = [
    "pandas>=1.3",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "Apache-2.0"}
[project.optional-dependencies]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest~=7.1",
]
